<!DOCTYPE html>
<html>
<head>
    <title>Administration</title>
</head>
<body>
    <div class="container">
        <?php
        if (isset($_SESSION['id'])) { // Vérifier si l'utilisateur est connecté
            // Inclure le contenu principal de la page (par exemple, la liste des clients)
            // Vous pouvez utiliser une variable $content pour passer le contenu à inclure
            if (isset($content)) {
                include $content;
            }
        } else {
            // Si l'utilisateur n'est pas connecté, inclure le formulaire de connexion
            if ($template === "index") {
                include __DIR__ . '/admins/connexion.php';
            }
        }
        ?>
    </div>
</body>
</html>